### ISSUE TITLE
Core endpoints provide bad profile for user - zone file cannot be loaded.

### ISSUE THREAD

**Issue by AC-FTW** [blockstack/blockstack-core#875] opened 2018-10-23 05:24 UTC
The profile provided for Blockstack ID naval.id features a zonefile URL that cannot be loaded, blocking this user's access to GAIA storage. Go to https://core.blockstack.org/v1/names/naval.id and try to load the zonefile URL provided (https://gaia.blockstack.org/hub/19rJSaipwUdFwS5iD7yMvAvtAYGA36fTDS/0/profile.json). It returns a BlobNotFound.

The problem can also be seen when trying to use GAIA gateway, https://gaia-gateway.com/naval.id/www.stealthy.im/pk.txt, which returns: {"error":"Failed to load profile for naval.id"}.

The search endpoint won't even return a result for user naval.id:  https://core.blockstack.org/v1/search?query=naval. It only returns one result for a different user "navaladi.id.blockstack".

We are seeing a variety of different behaviors for other important Blockstack user IDs as well, where the following behavior legend applies:

X - doesn't find
O - finds
D - downloads the profile

naval.id:
  - https://core.blockstack.org/v1/names/naval.id
  X https://gaia-gateway.com/naval.id
  X https://gaia.blockstack.org/hub/19rJSaipwUdFwS5iD7yMvAvtAYGA36fTDS/0/profile.json
  O https://gaia.blockstack.org/hub/19rJSaipwUdFwS5iD7yMvAvtAYGA36fTDS/profile.json

fred.id
  - https://core.blockstack.org/v1/names/fred.id
  O https://gaia-gateway.com/fred.id
  O https://gaia.blockstack.org/hub/1CER5u4QXuqffHjHKrU76iMCsqtJLM5VHu/0/profile.json
  X https://gaia.blockstack.org/hub/1CER5u4QXuqffHjHKrU76iMCsqtJLM5VHu/profile.json

fredwilson.id
  - https://core.blockstack.org/v1/names/fredwilson.id
  X https://gaia-gateway.com/fredwilson.id
  D https://gaia.blockstack.org/hub/1GSFLzRi4BzC4iQKDHypAfC5e4esYeM7DK/0/profile.json
  X https://gaia.blockstack.org/hub/1GSFLzRi4BzC4iQKDHypAfC5e4esYeM7DK/profile.json

werner.id
  - https://core.blockstack.org/v1/names/werner.id
  X https://gaia-gateway.com/werner.id
  X https://gaia.blockstack.org/hub/1DGwhkq2hJuMNn8QWYUXtbeqtkZc4Wpdac/0/profile.json
  X https://gaia.blockstack.org/hub/1DGwhkq2hJuMNn8QWYUXtbeqtkZc4Wpdac/profile.json

barrysilbert.id
  - https://core.blockstack.org/v1/names/barrysilbert.id
  O https://gaia-gateway.com/barrysilbert.id
  D https://gaia.blockstack.org/hub/1JzruCrL17GEByT3FwqSHD5i93eK9HU9S5/0/profile.json
  X https://gaia.blockstack.org/hub/1JzruCrL17GEByT3FwqSHD5i93eK9HU9S5/profile.json

**Comment by hstove** [comment] 2018-10-24 15:43
Hm, with Naval it seems like the issue is that the zonefile listed in his name result is wrong, as you noted. I like the idea of 'cleaning' the name lookup to try and find the right profile.json, because it seems like it's either in the `/0/profile.json` or just `/profile.json`.

**Comment by jcnelson** [comment] 2018-10-24 16:51
This appears to be a bug in the Browser, not in Core.  The Browser (ostensibly) knows how to handle these cases.  Closing this issue here; please re-open it against the Browser.

**Closed by jcnelson** 2018-10-24 16:51 UTC

**Comment by prabhaav** [comment] 2018-10-24 17:04
Moved: https://github.com/blockstack/blockstack-browser/issues/1717
