### ISSUE TITLE
Install error Linux Mint 17.3 x64

### ISSUE THREAD

**Issue by romseguy** [blockstack/blockstack-core#402] opened 2017-04-29 15:53 UTC
As a reminder, Linux Mint 17.3 is based on Ubuntu 14.04.

I ran the two install commands:
```
$ sudo apt-get update && sudo apt-get install -y python-pip python-dev libssl-dev libffi-dev rng-tools libgmp3-dev
$ sudo pip2 install blockstack --upgrade
```
The second one gave me following error:
```
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-v3g0hn-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/cffi
```

[Here](https://github.com/blockstack/blockstack/blob/master/docs/cli-installation.md) I found the command is simply `sudo pip install blockstack` instead of `sudo pip2 install blockstack --upgrade`. Running it yields:
```
Traceback (most recent call last):
  File "/usr/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/usr/local/lib/python2.7/dist-packages/packaging/requirements.py", line 9, in <module>
    from pyparsing import stringStart, stringEnd, originalTextFor, ParseException
ImportError: No module named pyparsing
```

**Comment by jcnelson** [comment] 2017-05-02 18:29
Hey @romseguy, this looks like a duplicate of this bug: https://github.com/blockstack/blockstack-core/issues/401

The solution is here: https://stackoverflow.com/questions/42181056/when-i-do-pip-version-it-show-the-error-as-importerror-no-module-named-pypars/42721488

**Comment by jackzampolin** [comment] 2018-01-11 23:10
Closing this as fixed 🎉

**Closed by jackzampolin** 2018-01-11 23:10 UTC
